### ISSUE TITLE
Consolidate function seems to be failing  often

### ISSUE THREAD

**Issue by radumas** [CivicTechTO/ttc_subway_times#65]
It has only been successful 3 times in the last month... when it should be running daily. 

![image](https://user-images.githubusercontent.com/10623872/61339573-4a3b8780-a80c-11e9-88a9-922152fd8358.png)

**Comment by radumas** [comment]
It's timing out
![image](https://user-images.githubusercontent.com/10623872/61552721-95c97d80-aa26-11e9-91ab-3b53ebea7f38.png)

**Comment by radumas** [comment]
Tried increasing memory size, which might speed it up, and doubling time-out time.

![image](https://user-images.githubusercontent.com/10623872/62584406-61591c80-b882-11e9-95fd-e9b6a4f6454d.png)

**Comment by radumas** [comment]
Some recent change to the consolidation function appears to bugging out

```python
[ERROR] TypeError: join() argument must be str or bytes, not 'NoneType'
Traceback (most recent call last):
  File "/var/task/src/ttc_api_scraper/consolidate.py", line 123, in handler
    _consolidate()
  File "/var/task/src/ttc_api_scraper/consolidate.py", line 62, in _consolidate
    scrape_path = os.path.join(dir, consoli_date)
  File "/var/lang/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/var/lang/lib/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
```

**Comment by radumas** [comment]
Just deployed fix.
